GET http://localhost:3000/user/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3R1ZGVudEBlc3ByaXQudG4iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTY0NjgxOTcyOSwiZXhwIjoxNjQ2ODE5Nzg5fQ.kf7IC92WZRAi6APtceeiqayQJCWBV1TmFPC3GpqdCos
###
GET http://localhost:3000/user/connect
Authorization: Bearer eyJhbGciOiJIUzIhdsuh1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3R1ZGVudEBlc3ByaXQudG4iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTY0NjgxOTcyOSwiZXhwIjoxNjQ2ODE5Nzg5fQ.kf7IC92WZRAi6APtceeiqayQJCWBV1TmFPC3GpqdCos
###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"mhamdi.mouheb12@esprit.tn",
    "Password":"123456Mo"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"admin@esprit.tn",
    "Password":"123456"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"teacher@esprit.tn",
    "Password":"123456"
}


###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"Student@esprit.tn",
    "Password":"123456"
}

