GET http://localhost:3000/user/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3R1ZGVudEBlc3ByaXQudG4iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTY0NjQ0NTQ1MywiZXhwIjoxNjQ2NDQ1NTEzfQ.ornTSMWPZ25iejVMk9usC0i3Q61ymT7us-KRmnyJvJg
###
GET http://localhost:3000/user/connect
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3R1ZGVudEBlc3ByaXQudG4iLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTY0NjQ0NTQ1MywiZXhwIjoxNjQ2NDQ1NTEzfQ.ornTSMWPZ25iejVMk9usC0i3Q61ymT7us-KRmnyJvJg

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"student@esprit.tn",
    "Password":"123456"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"student@esprit.tn",
    "Password":"123456"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"teacher@esprit.tn",
    "Password":"123456"
}


###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email":"student@esprit.tn",
    "Password":"123456"
}

